client_id = "bd5ae88d102a37bc3384dcaa75d3f205"
name = "download-tracker"
application_url = "https://dnd-technical-test-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# J'ai mis les scopes pour lire les clients (indispensable pour ton tracking Dn'D)
scopes = "read_customers,write_metaobjects"

[auth]
redirect_urls = [
  "https://dnd-technical-test-production.up.railway.app/auth/callback",
  "https://dnd-technical-test-production.up.railway.app/auth/shopify/callback",
  "https://admin.shopify.com/oauth/redirect-from-cli"
]

[app_proxy]
url = "https://dnd-technical-test-production.up.railway.app"
subpath = "downloads-tracker"
prefix = "apps"
